### Load Packages

In [13]:
import soccerdata as sd
import pandas as pd

pd.set_option('display.max_columns', None)

In [14]:
fb = sd.FBref('ESP-La Liga', '2025')

[09/02/26 04:51:42] INFO     Saving cached data to /Users/jacob129/soccerdata/data/FBref             ]8;id=448318;file:///opt/anaconda3/envs/football/lib/python3.13/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=448319;file:///opt/anaconda3/envs/football/lib/python3.13/site-packages/soccerdata/_common.py#250\250]8;;\

# Load Dataset

In [17]:
keeper = fb.read_team_match_stats(stat_type="keeper", team="Real Madrid", force_cache=False)

In [18]:
misc = fb.read_team_match_stats(stat_type="misc", team="Real Madrid", force_cache=False)

In [19]:
schedule = fb.read_team_match_stats(stat_type="schedule", team="Real Madrid", force_cache=False)

In [20]:
shooting = fb.read_team_match_stats(stat_type="shooting", team="Real Madrid", force_cache=False)

In [4]:
shooting2 = shooting.copy()

In [33]:
shooting2.tail()

                                                                          date  \

league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid      2026-05-03
                               2026-05-10 Barcelona-Real Madrid     2026-05-10
                               2026-05-14 Real Madrid-Oviedo        2026-05-14
                               2026-05-17 Sevilla-Real Madrid       2026-05-17
                               2026-05-23 Real Madrid-Athletic Club 2026-05-23

                                                                            round  \

league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid       Matchweek 34
                               2026-05-10 Barcelona-Real Madrid      Matchweek 35
                               2026-05-14 Real Madrid-Oviedo         Matchweek 36
                               2026-05-17 Sevilla-Real Madrid        Matchweek 37
                               2026-05-23 Real Madrid-Athletic Club  Matchweek 38

                                                                     day  \

league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid       Sun
                               2026-05-10 Barcelona-Real Madrid      Sun
                               2026-05-14 Real Madrid-Oviedo         Thu
                               2026-05-17 Sevilla-Real Madrid        Sun
                               2026-05-23 Real Madrid-Athletic Club  Sat

                                                                    venue  \

league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid       Away
                               2026-05-10 Barcelona-Real Madrid      Away
                               2026-05-14 Real Madrid-Oviedo         Home
                               2026-05-17 Sevilla-Real Madrid        Away
                               2026-05-23 Real Madrid-Athletic Club  Home

                                                                    result GF  \

league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid           W  2
                               2026-05-10 Barcelona-Real Madrid          L  0
                               2026-05-14 Real Madrid-Oviedo             W  2
                               2026-05-17 Sevilla-Real Madrid            W  1
                               2026-05-23 Real Madrid-Athletic Club      W  4

                                                                    GA  \

league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid       0
                               2026-05-10 Barcelona-Real Madrid      2
                               2026-05-14 Real Madrid-Oviedo         0
                               2026-05-17 Sevilla-Real Madrid        0
                               2026-05-23 Real Madrid-Athletic Club  2

                                                                          opponent  \

league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid            Espanyol
                               2026-05-10 Barcelona-Real Madrid          Barcelona
                               2026-05-14 Real Madrid-Oviedo                Oviedo
                               2026-05-17 Sevilla-Real Madrid              Sevilla
                               2026-05-23 Real Madrid-Athletic Club  Athletic Club

                                                                    Standard  \
                                                                         Gls
league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid             2
                               2026-05-10 Barcelona-Real Madrid            0
                               2026-05-14 Real Madrid-Oviedo               2
                               2026-05-17 Sevilla-Real Madrid              1
                               2026-05-23 Real Madrid-Athletic Club        4

                                                                             \
                                                                     Sh SoT
league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid       15   5
                               2026-05-10 Barcelona-Real Madrid       8   1
                               2026-05-14 Real Madrid-Oviedo         19   7
                               2026-05-17 Sevilla-Real Madrid        12   1
                               2026-05-23 Real Madrid-Athletic Club  13   8

                                                                           \
                                                                     SoT%
league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid       33.3
                               2026-05-10 Barcelona-Real Madrid      12.5
                               2026-05-14 Real Madrid-Oviedo         36.8
                               2026-05-17 Sevilla-Real Madrid         8.3
                               2026-05-23 Real Madrid-Athletic Club  61.5

                                                                           \
                                                                     G/Sh
league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid       0.13
                               2026-05-10 Barcelona-Real Madrid       0.0
                               2026-05-14 Real Madrid-Oviedo         0.11
                               2026-05-17 Sevilla-Real Madrid        0.08
                               2026-05-23 Real Madrid-Athletic Club  0.31

                                                                              \
                                                                    G/SoT PK
league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid        0.4  0
                               2026-05-10 Barcelona-Real Madrid       0.0  0
                               2026-05-14 Real Madrid-Oviedo         0.29  0
                               2026-05-17 Sevilla-Real Madrid         1.0  0
                               2026-05-23 Real Madrid-Athletic Club   0.5  0

                                                                           \
                                                                    PKatt
league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid          0
                               2026-05-10 Barcelona-Real Madrid         0
                               2026-05-14 Real Madrid-Oviedo            0
                               2026-05-17 Sevilla-Real Madrid           0
                               2026-05-23 Real Madrid-Athletic Club     0

                                                                         time  \

league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid       21:00:00
                               2026-05-10 Barcelona-Real Madrid      21:00:00
                               2026-05-14 Real Madrid-Oviedo         21:30:00
                               2026-05-17 Sevilla-Real Madrid        19:00:00
                               2026-05-23 Real Madrid-Athletic Club  21:00:00

                                                                                                          match_report  \

league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid       /en/matches/0b3f6b6c/Espanyol-Real-Madrid-May-...
                               2026-05-10 Barcelona-Real Madrid      /en/matches/3019c4d3/El-Clasico-Barcelona-Real...
                               2026-05-14 Real Madrid-Oviedo         /en/matches/46718a22/Real-Madrid-Oviedo-May-14...
                               2026-05-17 Sevilla-Real Madrid        /en/matches/39383d24/Sevilla-Real-Madrid-May-1...
                               2026-05-23 Real Madrid-Athletic Club  /en/matches/989dbbbf/Real-Madrid-Athletic-Club...

                                                                      is_w  \

league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid        True
                               2026-05-10 Barcelona-Real Madrid      False
                               2026-05-14 Real Madrid-Oviedo          True
                               2026-05-17 Sevilla-Real Madrid         True
                               2026-05-23 Real Madrid-Athletic Club   True

                                                                    after_new_coach

league      season team        game
ESP-La Liga 2526   Real Madrid 2026-05-03 Espanyol-Real Madrid                 True
                               2026-05-10 Barcelona-Real Madrid                True
                               2026-05-14 Real Madrid-Oviedo                   True
                               2026-05-17 Sevilla-Real Madrid                  True
                               2026-05-23 Real Madrid-Athletic Club            True

# Create Columns

In [ ]:
shooting2["is_w"] = shooting2["result"] == "W"

In [30]:
shooting2["after_new_coach"] = shooting2["date"] > "2026-01-12"

In [6]:
shooting2["goal_diff"] = shooting2["GF"] - shooting2["GA"]

In [21]:
keeper_cols = [(  'Performance',  'SoTA'),
            (  'Performance',    'GA'),
            (  'Performance', 'Saves'),
            (  'Performance', 'Save%'),
            (  'Performance',    'CS'),
            ('Penalty Kicks', 'PKatt'),
            ('Penalty Kicks',   'PKA'),
            ('Penalty Kicks',  'PKsv'),
            ('Penalty Kicks',   'PKm')]

misc_cols = [( 'Performance',  'CrdY'),
            ( 'Performance',  'CrdR'),
            ( 'Performance', '2CrdY'),
            ( 'Performance',   'Fls'),
            ( 'Performance',   'Fld'),
            ( 'Performance',   'Off'),
            ( 'Performance',   'Crs'),
            ( 'Performance',   'Int'),
            ( 'Performance',  'TklW'),
            ( 'Performance', 'PKwon'),
            ( 'Performance', 'PKcon')]

schedule_cols = ["Poss", "Captain", "Formation", "Opp Formation"]

In [9]:
shooting2["goal_diff"].value_counts().sum()

np.int64(38)

In [34]:
shooting2.groupby("after_new_coach")["is_w"].mean()

after_new_coach
False    0.736842
True     0.684211
Name: is_w, dtype: Float64

In [7]:
shooting.groupby("venue")["GF"].mean()

venue
Away    1.684211
Home    2.368421
Name: GF, dtype: Float64

In [10]:
shooting.groupby("day")["GA"].count()`

day
Fri     3
Mon     1
Sat    14
Sun    15
Thu     1
Tue     3
Wed     1
Name: GA, dtype: Int64

In [36]:
shooting2["after_new_coach"].value_counts()

after_new_coach
False    19
True     19
Name: count, dtype: int64

# Join Columns

# join keeper
df = shooting.join(keeper[keeper_cols])

# join misc
df = df.join(misc[misc_cols])

# hack way to convert 2-level columns to 1-level columns
df.columns = ['_'.join(filter(None, col)).strip() for col in df.columns]

# join schedule
df = df.join(schedule[schedule_cols])

In [24]:
df.head(10)

                                                                            date  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna         2025-08-19
                               2025-08-24 Oviedo-Real Madrid          2025-08-24
                               2025-08-30 Real Madrid-Mallorca        2025-08-30
                               2025-09-13 Real Sociedad-Real Madrid   2025-09-13
                               2025-09-20 Real Madrid-Espanyol        2025-09-20
                               2025-09-23 Levante-Real Madrid         2025-09-23
                               2025-09-27 Atlético Madrid-Real Madrid 2025-09-27
                               2025-10-04 Real Madrid-Villarreal      2025-10-04
                               2025-10-19 Getafe-Real Madrid          2025-10-19
                               2025-10-26 Real Madrid-Barcelona       2025-10-26

                                                                              round  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna           Matchweek 1
                               2025-08-24 Oviedo-Real Madrid            Matchweek 2
                               2025-08-30 Real Madrid-Mallorca          Matchweek 3
                               2025-09-13 Real Sociedad-Real Madrid     Matchweek 4
                               2025-09-20 Real Madrid-Espanyol          Matchweek 5
                               2025-09-23 Levante-Real Madrid           Matchweek 6
                               2025-09-27 Atlético Madrid-Real Madrid   Matchweek 7
                               2025-10-04 Real Madrid-Villarreal        Matchweek 8
                               2025-10-19 Getafe-Real Madrid            Matchweek 9
                               2025-10-26 Real Madrid-Barcelona        Matchweek 10

                                                                       day  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna          Tue
                               2025-08-24 Oviedo-Real Madrid           Sun
                               2025-08-30 Real Madrid-Mallorca         Sat
                               2025-09-13 Real Sociedad-Real Madrid    Sat
                               2025-09-20 Real Madrid-Espanyol         Sat
                               2025-09-23 Levante-Real Madrid          Tue
                               2025-09-27 Atlético Madrid-Real Madrid  Sat
                               2025-10-04 Real Madrid-Villarreal       Sat
                               2025-10-19 Getafe-Real Madrid           Sun
                               2025-10-26 Real Madrid-Barcelona        Sun

                                                                      venue  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna          Home
                               2025-08-24 Oviedo-Real Madrid           Away
                               2025-08-30 Real Madrid-Mallorca         Home
                               2025-09-13 Real Sociedad-Real Madrid    Away
                               2025-09-20 Real Madrid-Espanyol         Home
                               2025-09-23 Levante-Real Madrid          Away
                               2025-09-27 Atlético Madrid-Real Madrid  Away
                               2025-10-04 Real Madrid-Villarreal       Home
                               2025-10-19 Getafe-Real Madrid           Away
                               2025-10-26 Real Madrid-Barcelona        Home

                                                                      result  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna              W
                               2025-08-24 Oviedo-Real Madrid               W
                               2025-08-30 Real Madrid-Mallorca             W
                               2025-09-13 Real Sociedad-Real Madrid        W
                               2025-09-20 Real Madrid-Espanyol             W
                               2025-09-23 Levante-Real Madrid              W
                               2025-09-27 Atlético Madrid-Real Madrid      L
                               2025-10-04 Real Madrid-Villarreal           W
                               2025-10-19 Getafe-Real Madrid               W
                               2025-10-26 Real Madrid-Barcelona            W

                                                                       GF  GA  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna           1   0
                               2025-08-24 Oviedo-Real Madrid            3   0
                               2025-08-30 Real Madrid-Mallorca          2   1
                               2025-09-13 Real Sociedad-Real Madrid     2   1
                               2025-09-20 Real Madrid-Espanyol          2   0
                               2025-09-23 Levante-Real Madrid           4   1
                               2025-09-27 Atlético Madrid-Real Madrid   2   5
                               2025-10-04 Real Madrid-Villarreal        3   1
                               2025-10-19 Getafe-Real Madrid            1   0
                               2025-10-26 Real Madrid-Barcelona         2   1

                                                                              opponent  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                  Osasuna
                               2025-08-24 Oviedo-Real Madrid                    Oviedo
                               2025-08-30 Real Madrid-Mallorca                Mallorca
                               2025-09-13 Real Sociedad-Real Madrid      Real Sociedad
                               2025-09-20 Real Madrid-Espanyol                Espanyol
                               2025-09-23 Levante-Real Madrid                  Levante
                               2025-09-27 Atlético Madrid-Real Madrid  Atlético Madrid
                               2025-10-04 Real Madrid-Villarreal            Villarreal
                               2025-10-19 Getafe-Real Madrid                    Getafe
                               2025-10-26 Real Madrid-Barcelona              Barcelona

                                                                       Standard_Gls  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                     1
                               2025-08-24 Oviedo-Real Madrid                      3
                               2025-08-30 Real Madrid-Mallorca                    2
                               2025-09-13 Real Sociedad-Real Madrid               2
                               2025-09-20 Real Madrid-Espanyol                    2
                               2025-09-23 Levante-Real Madrid                     4
                               2025-09-27 Atlético Madrid-Real Madrid             2
                               2025-10-04 Real Madrid-Villarreal                  3
                               2025-10-19 Getafe-Real Madrid                      1
                               2025-10-26 Real Madrid-Barcelona                   2

                                                                       Standard_Sh  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                   18
                               2025-08-24 Oviedo-Real Madrid                    26
                               2025-08-30 Real Madrid-Mallorca                  17
                               2025-09-13 Real Sociedad-Real Madrid             16
                               2025-09-20 Real Madrid-Espanyol                  16
                               2025-09-23 Levante-Real Madrid                   24
                               2025-09-27 Atlético Madrid-Real Madrid            6
                               2025-10-04 Real Madrid-Villarreal                26
                               2025-10-19 Getafe-Real Madrid                    23
                               2025-10-26 Real Madrid-Barcelona                 23

                                                                       Standard_SoT  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                     5
                               2025-08-24 Oviedo-Real Madrid                     10
                               2025-08-30 Real Madrid-Mallorca                    7
                               2025-09-13 Real Sociedad-Real Madrid               6
                               2025-09-20 Real Madrid-Espanyol                    5
                               2025-09-23 Levante-Real Madrid                    10
                               2025-09-27 Atlético Madrid-Real Madrid             2
                               2025-10-04 Real Madrid-Villarreal                  7
                               2025-10-19 Getafe-Real Madrid                     10
                               2025-10-26 Real Madrid-Barcelona                  10

                                                                       Standard_SoT%  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                   27.8
                               2025-08-24 Oviedo-Real Madrid                    38.5
                               2025-08-30 Real Madrid-Mallorca                  41.2
                               2025-09-13 Real Sociedad-Real Madrid             37.5
                               2025-09-20 Real Madrid-Espanyol                  31.3
                               2025-09-23 Levante-Real Madrid                   41.7
                               2025-09-27 Atlético Madrid-Real Madrid           33.3
                               2025-10-04 Real Madrid-Villarreal                26.9
                               2025-10-19 Getafe-Real Madrid                    43.5
                               2025-10-26 Real Madrid-Barcelona                 43.5

                                                                       Standard_G/Sh  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                    0.0
                               2025-08-24 Oviedo-Real Madrid                    0.12
                               2025-08-30 Real Madrid-Mallorca                  0.12
                               2025-09-13 Real Sociedad-Real Madrid             0.13
                               2025-09-20 Real Madrid-Espanyol                  0.13
                               2025-09-23 Levante-Real Madrid                   0.13
                               2025-09-27 Atlético Madrid-Real Madrid           0.33
                               2025-10-04 Real Madrid-Villarreal                0.08
                               2025-10-19 Getafe-Real Madrid                    0.04
                               2025-10-26 Real Madrid-Barcelona                 0.09

                                                                       Standard_G/SoT  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                     0.0
                               2025-08-24 Oviedo-Real Madrid                      0.3
                               2025-08-30 Real Madrid-Mallorca                   0.29
                               2025-09-13 Real Sociedad-Real Madrid              0.33
                               2025-09-20 Real Madrid-Espanyol                    0.4
                               2025-09-23 Levante-Real Madrid                     0.3
                               2025-09-27 Atlético Madrid-Real Madrid             1.0
                               2025-10-04 Real Madrid-Villarreal                 0.29
                               2025-10-19 Getafe-Real Madrid                      0.1
                               2025-10-26 Real Madrid-Barcelona                   0.2

                                                                       Standard_PK  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                    1
                               2025-08-24 Oviedo-Real Madrid                     0
                               2025-08-30 Real Madrid-Mallorca                   0
                               2025-09-13 Real Sociedad-Real Madrid              0
                               2025-09-20 Real Madrid-Espanyol                   0
                               2025-09-23 Levante-Real Madrid                    1
                               2025-09-27 Atlético Madrid-Real Madrid            0
                               2025-10-04 Real Madrid-Villarreal                 1
                               2025-10-19 Getafe-Real Madrid                     0
                               2025-10-26 Real Madrid-Barcelona                  0

                                                                       Standard_PKatt  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                       1
                               2025-08-24 Oviedo-Real Madrid                        0
                               2025-08-30 Real Madrid-Mallorca                      0
                               2025-09-13 Real Sociedad-Real Madrid                 0
                               2025-09-20 Real Madrid-Espanyol                      0
                               2025-09-23 Levante-Real Madrid                       1
                               2025-09-27 Atlético Madrid-Real Madrid               0
                               2025-10-04 Real Madrid-Villarreal                    1
                               2025-10-19 Getafe-Real Madrid                        0
                               2025-10-26 Real Madrid-Barcelona                     1

                                                                           time  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna          21:00:00
                               2025-08-24 Oviedo-Real Madrid           21:30:00
                               2025-08-30 Real Madrid-Mallorca         21:30:00
                               2025-09-13 Real Sociedad-Real Madrid    16:15:00
                               2025-09-20 Real Madrid-Espanyol         16:15:00
                               2025-09-23 Levante-Real Madrid          21:30:00
                               2025-09-27 Atlético Madrid-Real Madrid  16:15:00
                               2025-10-04 Real Madrid-Villarreal       21:00:00
                               2025-10-19 Getafe-Real Madrid           21:00:00
                               2025-10-26 Real Madrid-Barcelona        16:15:00

                                                                                                            match_report  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna          /en/matches/d34e407e/Real-Madrid-Osasuna-Augus...
                               2025-08-24 Oviedo-Real Madrid           /en/matches/fde70dd0/Oviedo-Real-Madrid-August...
                               2025-08-30 Real Madrid-Mallorca         /en/matches/9c0a49c5/Real-Madrid-Mallorca-Augu...
                               2025-09-13 Real Sociedad-Real Madrid    /en/matches/980d729f/Real-Sociedad-Real-Madrid...
                               2025-09-20 Real Madrid-Espanyol         /en/matches/965b0ab3/Real-Madrid-Espanyol-Sept...
                               2025-09-23 Levante-Real Madrid          /en/matches/74a8527b/Levante-Real-Madrid-Septe...
                               2025-09-27 Atlético Madrid-Real Madrid  /en/matches/33523b09/El-Derbi-Madrileno-Atleti...
                               2025-10-04 Real Madrid-Villarreal       /en/matches/2aff6c8b/Real-Madrid-Villarreal-Oc...
                               2025-10-19 Getafe-Real Madrid           /en/matches/cc0d078a/Getafe-Real-Madrid-Octobe...
                               2025-10-26 Real Madrid-Barcelona        /en/matches/9c9d1f09/El-Clasico-Real-Madrid-Ba...

                                                                       Performance_SoTA  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                         0
                               2025-08-24 Oviedo-Real Madrid                          3
                               2025-08-30 Real Madrid-Mallorca                        3
                               2025-09-13 Real Sociedad-Real Madrid                   4
                               2025-09-20 Real Madrid-Espanyol                        1
                               2025-09-23 Levante-Real Madrid                         2
                               2025-09-27 Atlético Madrid-Real Madrid                 7
                               2025-10-04 Real Madrid-Villarreal                      2
                               2025-10-19 Getafe-Real Madrid                          1
                               2025-10-26 Real Madrid-Barcelona                       5

                                                                       Performance_GA  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                       0
                               2025-08-24 Oviedo-Real Madrid                        0
                               2025-08-30 Real Madrid-Mallorca                      1
                               2025-09-13 Real Sociedad-Real Madrid                 1
                               2025-09-20 Real Madrid-Espanyol                      0
                               2025-09-23 Levante-Real Madrid                       1
                               2025-09-27 Atlético Madrid-Real Madrid               5
                               2025-10-04 Real Madrid-Villarreal                    1
                               2025-10-19 Getafe-Real Madrid                        0
                               2025-10-26 Real Madrid-Barcelona                     1

                                                                       Performance_Saves  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                          0
                               2025-08-24 Oviedo-Real Madrid                           3
                               2025-08-30 Real Madrid-Mallorca                         2
                               2025-09-13 Real Sociedad-Real Madrid                    3
                               2025-09-20 Real Madrid-Espanyol                         1
                               2025-09-23 Levante-Real Madrid                          1
                               2025-09-27 Atlético Madrid-Real Madrid                  2
                               2025-10-04 Real Madrid-Villarreal                       1
                               2025-10-19 Getafe-Real Madrid                           1
                               2025-10-26 Real Madrid-Barcelona                        4

                                                                       Performance_Save%  \
league      season team        game
ESP-La Liga 2526   Real Madrid 2025-08-19 Real Madrid-Osasuna                       <NA>
                               2025-08-24 Oviedo-Real Madrid                       100.0
                               2025-08-30 Real Madrid-Mallorca                      66.7
                               2025-09-13 Real Sociedad-Real Madrid                 75.0